# Generated by Django 5.1.2 on 2024-10-30 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_category_alter_product_cost_price_and_more'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the sale was made.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the sale.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(help_text='User who made the sale.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(help_text='Product sold.', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(help_text='Sale to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, help_text='Sale price of the product.', max_digits=10),
        ),
    ]
